plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:report"))
    implementation(project(":core:news"))
    implementation(project(":core:sync"))
    implementation(project(":core:photo"))
    implementation(project(":core:metric"))
    implementation(project(":core:todo"))
    implementation(project(":core:article"))
    implementation(project(":core:identity"))
    implementation(project(":core:feed"))
    implementation(project(":core:login"))
    implementation(project(":core:user"))
    implementation(project(":core:document"))
    implementation(project(":core:audio"))
    implementation(project(":core:share"))
    implementation(project(":core:timer"))
    implementation(project(":core:cart"))
    implementation(project(":core:event"))
    implementation(project(":core:search"))
    implementation(project(":core:profile"))
    implementation(project(":core:alarm"))
    implementation(project(":core:status"))
    implementation(project(":core:map"))
    implementation(project(":core:network"))
    implementation(project(":core:push-contact"))
    implementation(project(":core:list"))
    implementation(project(":core:session"))
    implementation(project(":core:calendar"))
    implementation(project(":core:checkout"))
    implementation(project(":core:account"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}