plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:file-login"))
    implementation(project(":domain:account-login"))
    implementation(project(":domain:setting-login"))
    implementation(project(":domain:feed-login"))
    implementation(project(":domain:status-login"))
    implementation(project(":domain:map-login"))
    implementation(project(":domain:calendar-login"))
    implementation(project(":domain:login-login"))
    implementation(project(":domain:session-login"))
    implementation(project(":domain:alarm-login"))
    implementation(project(":domain:identity-login"))
    implementation(project(":domain:notification-login"))
    implementation(project(":domain:checkout-login"))
    implementation(project(":domain:event-login"))
    implementation(project(":domain:cart-login"))
    implementation(project(":domain:analytics-login"))
    implementation(project(":domain:media-login"))
    implementation(project(":domain:playlist-login"))
    implementation(project(":domain:sync-login"))
    implementation(project(":domain:timer-login"))
    implementation(project(":domain:user-login"))
    implementation(project(":domain:todo-login"))
    implementation(project(":domain:document-login"))
    implementation(project(":domain:metric-login"))
    implementation(project(":domain:video-login"))
    implementation(project(":domain:network-login"))
    implementation(project(":domain:list-login"))
    implementation(project(":domain:gallery-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}