plugins {
  id 'conventions.gradle-plugin'
}

conventions {
  gradlePlugin('spotlight') {
    id = "com.fueledbycaffeine.spotlight"
    implementationClass = "com.fueledbycaffeine.spotlight.SpotlightSettingsPlugin"
    displayName = "Spotlight"
    description = "A plugin that makes managing `settings.gradle(.kts)` for large projects easier"
    tags = ["IDE", "dependencies"]
  }
}

mavenPublishing {
  pom {
    name = "Spotlight Gradle plugin"
    description = "A Gradle plugin that and makes managing `settings.gradle(.kts)` for large projects easier"
  }
}

dependencies {
  api project(':buildscript-utils')

  compileOnly(libs.develocity)

  functionalTestApi libs.moshi
  functionalTestImplementation libs.truth
  functionalTestImplementation libs.moshi.kotlin
}
