plugins {
  id 'conventions.library'
  id 'conventions.moshi'
  id 'conventions.autoservice'
}

mavenPublishing {
  pom {
    name = "Spotlight buildscript utils"
    description = "Parse and build a DAG of your gradle projects"
  }
}

dependencies {
  api(libs.moshix.sealed.runtime)
  api(libs.moshi)

  implementation(libs.moshi.adapters)
  implementation(libs.okio)
}
